**MatSoc: Intro to ML Techniques**

**Assignment 3**

Deadline: Sunday, 14 January 2024, 23:59 IST

Name : Prabhanshu Choudhary

Roll Number : 220773

IITK Email : prabhanshu22@iitk.ac.in

You may use the ML library of your choice to do this part.

1. Train a neural network on tensorflow for the given data
2. Train a decision tree with sklearn for the given data
3. Make predictions using the ensemble (average) of the two datasets
4. Report the error for the the neural network, decision tree and the ensemble.
5. Use Sampling with replacement to increase the data size by 15 percent.
6. Use 15% of the increased data set as the test data.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

In [ ]:
uploaded=files.upload()
df=pd.read_csv('train_weekthree.csv')
df

Saving train_weekthree.csv to train_weekthree.csv


Number of times pregnant  \
0                           6   
1                           1   
2                           8   
3                           1   
4                           0   
..                        ...   
763                        10   
764                         2   
765                         5   
766                         1   
767                         1   

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                  148                          
1                                                   85                          
2                                                  183                          
3                                                   89                          
4                                                  137                          
..                                                 ...                          
763                                                101                          
764                                                122                          
765                                                121                          
766                                                126                          
767                                                 93                          

     Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                                  72                                35   
1                                  66                                29   
2                                  64                                 0   
3                                  66                                23   
4                                  40                                35   
..                                ...                               ...   
763                                76                                48   
764                                70                                27   
765                                72                                23   
766                                60                                 0   
767                                70                                31   

     2-Hour serum insulin (mu U/ml)  \
0                                 0   
1                                 0   
2                                 0   
3                                94   
4                               168   
..                              ...   
763                             180   
764                               0   
765                             112   
766                               0   
767                               0   

     Body mass index (weight in kg/(height in m)^2)  \
0                                              33.6   
1                                              26.6   
2                                              23.3   
3                                              28.1   
4                                              43.1   
..                                              ...   
763                                            32.9   
764                                            36.8   
765                                            26.2   
766                                            30.1   
767                                            30.4   

     Diabetes pedigree function  Age (years)  Class variable (0 or 1)  
0                         0.627           50                        1  
1                         0.351           31                        0  
2                         0.672           32                        1  
3                         0.167           21                        0  
4                         2.288           33                        1  
..                          ...          ...                      ...  
763                       0.171           63                        0  
764                       0.

In [ ]:
df.isnull().sum()

Number of times pregnant                                                    0
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    0
Diastolic blood pressure (mm Hg)                                            0
Triceps skin fold thickness (mm)                                            0
2-Hour serum insulin (mu U/ml)                                              0
Body mass index (weight in kg/(height in m)^2)                              0
Diabetes pedigree function                                                  0
Age (years)                                                                 0
Class variable (0 or 1)                                                     0
dtype: int64

In [ ]:
df.describe()

Number of times pregnant  \
count                768.000000   
mean                   3.845052   
std                    3.369578   
min                    0.000000   
25%                    1.000000   
50%                    3.000000   
75%                    6.000000   
max                   17.000000   

       Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
count                                         768.000000                          
mean                                          120.894531                          
std                                            31.972618                          
min                                             0.000000                          
25%                                            99.000000                          
50%                                           117.000000                          
75%                                           140.250000                          
max                                           199.000000                          

       Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
count                        768.000000                        768.000000   
mean                          69.105469                         20.536458   
std                           19.355807                         15.952218   
min                            0.000000                          0.000000   
25%                           62.000000                          0.000000   
50%                           72.000000                         23.000000   
75%                           80.000000                         32.000000   
max                          122.000000                         99.000000   

       2-Hour serum insulin (mu U/ml)  \
count                      768.000000   
mean                        79.799479   
std                        115.244002   
min                          0.000000   
25%                          0.000000   
50%                         30.500000   
75%                        127.250000   
max                        846.000000   

       Body mass index (weight in kg/(height in m)^2)  \
count                                      768.000000   
mean                                        31.992578   
std                                          7.884160   
min                                          0.000000   
25%                                         27.300000   
50%                                         32.000000   
75%                                         36.600000   
max                                         67.100000   

       Diabetes pedigree function  Age (years)  Class variable (0 or 1)  
count                  768.000000   768.000000               768.000000  
mean                     0.471876    33.240885                 0.348958  
std                      0.331329    11.760232                 0.476951  
min                      0.078000    21.000000                 0.000000  
25%                      0.243750    24.000000                 0.000000  
50%                      0.372500    29.000000                 0.000000  
75%                      0.626250    41.000000                 1.000000  
max                      2.420000    81.000000                 1.000000

In [ ]:
#Train a neural network on tensorflow for the given data

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Create a neural network model
model1 = keras.Sequential([
    layers.Dense(10, activation='relu'),
    layers.Dense(10, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

# Compile the model
model1.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train the model
model1.fit(df.drop('Class variable (0 or 1)', axis=1), df['Class variable (0 or 1)'], epochs=25)

# Evaluate the model
model1.evaluate(df.drop('Class variable (0 or 1)', axis=1), df['Class variable (0 or 1)'])

Epoch 1/25
24/24 [==============================] - 1s 2ms/step - loss: 12.5142 - accuracy: 0.6615
Epoch 2/25
24/24 [==============================] - 0s 2ms/step - loss: 6.5490 - accuracy: 0.6250
Epoch 3/25
24/24 [==============================] - 0s 2ms/step - loss: 3.3239 - accuracy: 0.5807
Epoch 4/25
24/24 [==============================] - 0s 2ms/step - loss: 2.0528 - accuracy: 0.5286
Epoch 5/25
24/24 [==============================] - 0s 3ms/step - loss: 1.3075 - accuracy: 0.5547
Epoch 6/25
24/24 [==============================] - 0s 2ms/step - loss: 1.0040 - accuracy: 0.5872
Epoch 7/25
24/24 [==============================] - 0s 2ms/step - loss: 0.8773 - accuracy: 0.5729
Epoch 8/25
24/24 [==============================] - 0s 2ms/step - loss: 0.8312 - accuracy: 0.6003
Epoch 9/25
24/24 [==============================] - 0s 2ms/step - loss: 0.7516 - accuracy: 0.6341
Epoch 10/25
24/24 [==============================] - 0s 2ms/step - loss: 0.7268 - accuracy: 0.6341
Epoch 11/25
24/24 

[0.6006259918212891, 0.6979166865348816]

In [ ]:
#Train a decision tree with sklearn for the given data

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(df.drop('Class variable (0 or 1)', axis=1), df['Class variable (0 or 1)'], test_size=0.2)
# Create a decision tree model
model2 = DecisionTreeClassifier()
# Train the model
model2.fit(X_train, y_train)
# Evaluate the model
model2.score(X_test, y_test)

0.7207792207792207

In [ ]:
# Make predictions using the ensemble (average) of the two datasets
y_pred_nn=model1.predict(df.drop('Class variable (0 or 1)', axis=1))
y_pred_dt=model2.predict(df.drop('Class variable (0 or 1)', axis=1))
y_pred_ensemble = (y_pred_nn + y_pred_dt) / 2
print(y_pred_ensemble)

24/24 [==============================] - 0s 2ms/step
[[0.91502103 0.41502103 0.91502103 ... 0.41502103 0.41502103 0.41502103]
 [0.58878958 0.08878958 0.58878958 ... 0.08878958 0.08878958 0.08878958]
 [0.88529438 0.38529438 0.88529438 ... 0.38529438 0.38529438 0.38529438]
 ...
 [0.645404   0.145404   0.645404   ... 0.145404   0.145404   0.145404  ]
 [0.89370963 0.39370963 0.89370963 ... 0.39370963 0.39370963 0.39370963]
 [0.57419031 0.07419031 0.57419031 ... 0.07419031 0.07419031 0.07419031]]


In [ ]:
from sklearn.metrics import mean_absolute_error

# Assuming y_true are the true labels and y_pred_nn are the predicted labels by the neural network
error_nn = mean_absolute_error(df['Class variable (0 or 1)'], y_pred_nn)

# Similarly, calculate the mean absolute error for the decision tree
error_dt = mean_absolute_error(df['Class variable (0 or 1)'], y_pred_dt)

print('Mean Absolute Error for the neural network:', error_nn)
print('Mean Absolute Error for the decision tree:', error_dt)


Mean Absolute Error for the neural network: 0.38293724191559403
Mean Absolute Error for the decision tree: 0.055989583333333336


In [ ]:
df['Class variable (0 or 1)'].shape

(768,)

In [ ]:
y_pred_ensemble.shape

(768, 768)

In [ ]:
from sklearn.metrics import mean_absolute_error
y_pred_ensemble_1d = y_pred_ensemble.flatten()  # Flatten the array into 1-dimensional format

# Ensure that the length of the predicted values matches the length of true labels
y_pred_ensemble_matched = y_pred_ensemble_1d[:len(df)]

error_ensemble = mean_absolute_error(df['Class variable (0 or 1)'], y_pred_ensemble_matched)
print('Mean Absolute Error for the ensemble:', error_ensemble)


[0.91502103 0.41502103 0.91502103 ... 0.07419031 0.07419031 0.07419031]
Mean Absolute Error for the ensemble: 0.3278448951120178


In [ ]:
#Use Sampling with replacement to increase the data size by 15 percent.

df1=df.sample(frac=1.15,replace=True)
df1.shape


(883, 9)

In [ ]:
# Use 15% of the increased data set as the test data

X_train, X_test, y_train, y_test = train_test_split(df1.drop('Class variable (0 or 1)', axis=1), df1['Class variable (0 or 1)'], test_size=0.15)
# Create a decision tree model
model2 = DecisionTreeClassifier()
# Train the model
model2.fit(X_train, y_train)
# Evaluate the model
model2.score(X_test, y_test)


0.8646616541353384